os: linux
services:
    - docker
sudo: required
language: python
env:
    global:
        - CONAN_UPLOAD=1
        - CONAN_REFERENCE=QtBase/5.7.1
        - CONAN_USERNAME=russelltg
        - CONAN_CHANNEL=stable
        - CONAN_USER_DOCKER=1
        
    matrix:
        - CONAN_GCC_VERSIONS=4.8
        - CONAN_GCC_VERSIONS=4.9
        - CONAN_GCC_VERSIONS=5.2
        - CONAN_GCC_VERSIONS=5.3
        - CONAN_GCC_VERSIONS=5.4
        - CONAN_GCC_VERSIONS=6.1
        - CONAN_GCC_VERSIONS=6.2
        


install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
