os: linux
services:
    - docker
sudo: required
language: python
env:
    global:
        - CONAN_UPLOAD=1
        - CONAN_REFERENCE=QtBase/5.7.1
        - CONAN_USERNAME=russelltg
        - CONAN_CHANNEL=stable
        - CONAN_USE_DOCKER=1  
        - CONAN_TOTAL_PAGES=4
        
        secure: "vB+3nlAUXvVaMfVGYSES9kpfoopDu/DPInX3BSFAuW8WjTM38DhkR4eeFxqn4sTnrjqzatKgMoslZbDbTAfndLGjwqiAHl7+3VsUFxG3MHGffdHEdhpy6plUO3xrkWZvY4V+dY0PoCrpuvh1ZBGl1JzbmYMqa7NCmvqMtc9/J8/iglZPy44EhEEWE4jYZbd3RYGXIkizVJFoNXXJuas9C6zYEMJXXBKBI3jxBp2NmbaltuWhyLKtJBibSEVs6Ubo7Gll7c9Fda1BqSRupGXkzAw1uRxNY978CpHZ4ar96KBvW9x14r4p0IRIzUk0eACv7d+FBtw6qoOztDizEgeHUAg8FRfjbM9JBRx/1wsXhDWMphtEjktZCqaMIMsI0bXA9cAwkG3O3arq4HTjEY1ojL8fwlnKhkRZdcYuxu1CGcTPJXDfEJAr8729uEVuFJhSrVU89ccqfoamOxx5LXDZZMTQr2NyRi8Kz7lSu5XzsJJHVFaY8DQemK9qmgLhvp1T3XQ+Iyd4MocDB0grYtGJgX+mu+zAq7L3YGdnmWhWEdi2dLU2UTTyXFs57jzjSqpW2BhP3u3PjFbI+/D1eIPTnceApm7mHLdTDu/DfcJ7goj3nUDKslr8sOfNWEL0tcE1Gw4omHUb/gO7u6JGMD835HtLpzYb6y7aeSwCLaKbGPk="

        
    matrix:
        - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=1
        - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=2
        - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=3
        - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=4
        
        - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=1
        - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=2
        - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=3
        - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=4
        
        - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=1
        - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=2
        - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=3
        - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=4
        
        - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=1
        - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=2
        - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=3
        - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=4
        
        - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=1
        - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=2
        - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=3
        - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=4
        
        - CONAN_GCC_VERSIONS=6.1 CONAN_CURRENT_PAGE=1
        - CONAN_GCC_VERSIONS=6.1 CONAN_CURRENT_PAGE=2
        - CONAN_GCC_VERSIONS=6.1 CONAN_CURRENT_PAGE=3
        - CONAN_GCC_VERSIONS=6.1 CONAN_CURRENT_PAGE=4
        
        - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=1
        - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=2
        - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=3
        - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=4

matrix:
   include:
       - os: osx
         osx_image: xcode8 # apple-clang 8
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx
         osx_image: xcode8 # apple-clang 8
         language: generic
         env: CONAN_CURRENT_PAGE=2
       - os: osx
         osx_image: xcode8 # apple-clang 8
         language: generic
         env: CONAN_CURRENT_PAGE=3
       - os: osx
         osx_image: xcode8 # apple-clang 8
         language: generic
         env: CONAN_CURRENT_PAGE=4

       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=2
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=3
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=4
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=5
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=6
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=7
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=8
         

       - os: osx 
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx 
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=2
       - os: osx 
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=3
       - os: osx 
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=4
       - os: osx 
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=5
       - os: osx 
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=6
       - os: osx 
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=7
       - os: osx 
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=8
        



install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
